deployment_slug: oblab
scenario: token-only
portal_url: http://auth.example.com
client_id: pam-access
client_id_policy: fixed
client_secret_mode: embedded
embedded_client_secret: pamsecret
server_group: bastion
server_group_policy: fixed
target_role: bastion
auto_enroll_setup: yes
ansible_auto_approve: yes
apt_url: http://192.168.122.1:8088
apt_suite: ./
apt_component: ""
enable_hardening: no
enable_audit_trace: no
disable_session_recorder: no
self_delete: no
