/*
 * ob-record-sink - privileged session-recording sink
 *
 * Socket-activated (systemd, Accept=yes): one short-lived instance per
 * connection. Implements the tamper-evident recording design
 * (doc/design/tamper-evident-session-recording.rst, #151).
 *
 * The unprivileged ob-session-recorder (running as the logged-in user) connects
 * via ob-record-connect and sends:
 *   - line 1: a one-line JSON metadata HEADER, then
 *   - the opaque recording STREAM (typescript bytes) until EOF.
 *
 * This sink:
 *   1. derives the recorded user from the connection's SO_PEERCRED. This is the
 *      ONLY source of identity — kernel-verified, never from the header — so a
 *      caller can only ever write under its own name (no cross-user forgery,
 *      no path traversal: the <user> path component is not client-controlled).
 *   2. creates /var/lib/open-bastion/sessions/<user>/ (root:ob-sessions 0750)
 *      and writes the recording + metadata there, root-owned (files 0640). The
 *      recorded user is NOT in ob-sessions and the tree is o-rwx, so the user
 *      cannot list, read, unlink or truncate its own recording — which is the
 *      whole point (#151).
 *   3. records ONLY what it observes: status active -> completed (clean EOF) /
 *      truncated (size or duration cap) / aborted (abnormal drop, or the peer
 *      died while the connection was held open elsewhere). The child
 *      command's exit code is deliberately not recorded (it would be entirely
 *      client-reported; see the design §5).
 *
 * An idle stream is NOT an abnormal end: an interactive session can print
 * nothing for hours. The sink bounds a connection by the recorder's own
 * liveness (the SO_PEERCRED pid), a total duration and a byte cap -- never by
 * silence (#287).
 *
 * Threat model: root is trusted; we defend only against the unprivileged user.
 *
 * Copyright (C) 2026 Linagora
 * License: AGPL-3.0
 */

#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <grp.h>
#include <limits.h>
#include <poll.h>
#include <pwd.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

#include <json-c/json.h>

#include "ob_cert_proto.h" /* ob_read_line, ob_valid_username */

#define OB_RECORD_SINK_VERSION "0.1.0"

#define SESSIONS_DIR "/var/lib/open-bastion/sessions"
#define SESSIONS_GROUP "ob-sessions"

/* Header line cap (one JSON object). */
#define MAX_HEADER 8192
/* Per-session recording byte cap: bound a hostile/runaway stream. Generous for
 * legitimate long interactive sessions; exceeding it finalizes as "truncated". */
#define MAX_RECORDING (1024L * 1024L * 1024L) /* 1 GiB */
/* Field bounds for header metadata (informational, JSON-escaped on output). */
#define MAX_CMD 8192
#define MAX_SHORT 256
/* The header is written right after connect(); a peer that has not sent it
 * by then is not a recorder. This bounds the HEADER only: once the stream
 * starts, silence is normal and never ends a recording (#287). */
#define HEADER_TIMEOUT_SEC 30
/* How long an idle stream sleeps before the sink checks that the peer is
 * still alive and the session is within its duration cap. Overridable by
 * OB_RECORD_POLL_SEC in the daemon's environment (tests use 1). */
#define DEFAULT_POLL_SEC 30
/* Total duration cap of one recording (7 days); reaching it finalizes as
 * "truncated". Overridable by OB_RECORD_MAX_SEC in the daemon's environment. */
#define DEFAULT_MAX_SESSION_SEC (7L * 24L * 3600L)
#define COPY_BUF (64 * 1024)

static void fail(const char *msg)
{
    /* stderr -> journal (StandardError=journal). Never log recording content. */
    fprintf(stderr, "[ob-record-sink] %s\n", msg);
}

/* A session-id is generated by the recorder (a UUID). Accept a conservative
 * charset/length so it is safe as a path component. */
static int valid_session_id(const char *s)
{
    if (!s || !*s || strlen(s) > 64)
        return 0;
    for (const char *p = s; *p; p++)
        if (!(isalnum((unsigned char)*p) || *p == '-' || *p == '_'))
            return 0;
    return 1;
}

/* Read a string field from the parsed header, bounded by max. Returns a malloc'd
 * copy (caller frees) or NULL when absent/too long/contains control chars other
 * than what json already decoded; control chars are tolerated (json-c re-escapes
 * on output) but length is enforced. */
static char *hdr_str(struct json_object *h, const char *key, size_t max)
{
    struct json_object *v;
    if (!json_object_object_get_ex(h, key, &v))
        return NULL;
    if (!json_object_is_type(v, json_type_string))
        return NULL;
    const char *s = json_object_get_string(v);
    if (!s || strlen(s) > max)
        return NULL;
    return strdup(s);
}

/* ISO-8601 UTC timestamp into buf. */
static void iso_utc(char *buf, size_t n)
{
    time_t t = time(NULL);
    struct tm tm;
    gmtime_r(&t, &tm);
    strftime(buf, n, "%Y-%m-%dT%H:%M:%SZ", &tm);
}

/* Resolve the ob-sessions gid; fall back to 0 (root) with a warning if absent
 * (the setup scripts create the group; a missing group must not relax to a
 * user-accessible mode). */
static gid_t sessions_gid(void)
{
    char buf[4096];
    struct group gr, *grp = NULL;
    if (getgrnam_r(SESSIONS_GROUP, &gr, buf, sizeof(buf), &grp) == 0 && grp)
        return grp->gr_gid;
    fail("group " SESSIONS_GROUP " not found; falling back to root group");
    return 0;
}

/* A positive number of seconds from the daemon's own environment, or def when
 * unset or malformed. Like OB_SESSIONS_DIR below, this is the environment the
 * systemd unit gives the sink, never anything the connecting client sends. */
static long env_seconds(const char *name, long def, long max)
{
    const char *e = getenv(name);
    if (!e || !*e)
        return def;
    char *end = NULL;
    errno = 0;
    long v = strtol(e, &end, 10);
    if (errno != 0 || !end || *end != '\0' || v <= 0 || v > max) {
        fail("ignoring a malformed timing override in the unit environment");
        return def;
    }
    return v;
}

static long mono_now(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long)ts.tv_sec;
}

/* A pidfd for the process that connected, so that its exit wakes the copy
 * loop. SO_PEERPIDFD (Linux 6.5+) names that very process, with no pid-reuse
 * window; pidfd_open() on the SO_PEERCRED pid is the next best thing. Returns
 * -1 when neither is available -- an older kernel, or a SystemCallFilter
 * without pidfd_open -- and the caller then falls back to kill(pid, 0) at
 * each idle wake-up. */
static int peer_pidfd(int conn_fd, pid_t pid)
{
#ifdef SO_PEERPIDFD
    int pfd = -1;
    socklen_t plen = sizeof(pfd);
    if (getsockopt(conn_fd, SOL_SOCKET, SO_PEERPIDFD, &pfd, &plen) == 0 && pfd >= 0)
        return pfd;
#endif
#ifdef SYS_pidfd_open
    if (pid > 0) {
        long r = syscall(SYS_pidfd_open, pid, 0);
        if (r >= 0)
            return (int)r;
    }
#endif
    (void)conn_fd;
    (void)pid;
    return -1;
}

/* Fallback liveness probe. A pid of 0 (peer in another pid namespace) cannot
 * be checked and counts as alive: the duration cap still bounds it. */
static int pid_alive(pid_t pid)
{
    if (pid <= 0)
        return 1;
    return kill(pid, 0) == 0 || errno == EPERM;
}

/* Base sessions directory. Hard-coded by default; OB_SESSIONS_DIR overrides it
 * for tests. This reads the DAEMON's own environment, which is set by the systemd
 * unit (not by the connecting client), so it is not an attacker-controlled
 * input. */
static const char *sessions_base(void)
{
    const char *e = getenv("OB_SESSIONS_DIR");
    return (e && *e) ? e : SESSIONS_DIR;
}

/* Enforce root:gid ownership and mode on an open fd. In production the sink runs
 * as root and this is a SECURITY requirement: if a legacy user-owned dir or file
 * kept the user's ownership/write, the user could unlink/truncate root files —
 * so a failure here must FAIL CLOSED (refuse the session). When NOT running as
 * root (dev/test via OB_SESSIONS_DIR) the privilege model does not apply and the
 * call cannot succeed anyway, so we only warn. Returns 0 ok / -1 fatal. */
static int enforce_owner_mode(int fd, gid_t gid, mode_t mode, const char *what)
{
    int is_root = (geteuid() == 0);
    if (fchown(fd, 0, gid) != 0) {
        if (is_root) {
            fail(what);
            fail("cannot enforce root ownership; refusing (fail-closed)");
            return -1;
        }
        fail("fchown failed, not root (dev/test) — continuing");
    }
    if (fchmod(fd, mode) != 0) {
        if (is_root) {
            fail(what);
            fail("cannot enforce mode; refusing (fail-closed)");
            return -1;
        }
        fail("fchmod failed, not root (dev/test) — continuing");
    }
    return 0;
}

/* Ensure <base>/<user> exists, root:gid 0750, no symlinks. Returns a dir
 * fd (O_DIRECTORY|O_NOFOLLOW) on success, -1 on error. */
static int ensure_user_dir(const char *user, gid_t gid)
{
    char path[512];
    int n = snprintf(path, sizeof(path), "%s/%s", sessions_base(), user);
    if (n < 0 || (size_t)n >= sizeof(path)) {
        fail("session dir path too long");
        return -1;
    }

    int fd = open(path, O_RDONLY | O_DIRECTORY | O_NOFOLLOW);
    if (fd < 0) {
        if (mkdir(path, 0750) != 0 && errno != EEXIST) {
            fail("mkdir(session dir) failed");
            return -1;
        }
        fd = open(path, O_RDONLY | O_DIRECTORY | O_NOFOLLOW);
        if (fd < 0) {
            fail("open(session dir) after mkdir failed");
            return -1;
        }
    }
    /* Enforce ownership/mode on the fd (no TOCTOU, no symlink). Fail closed as
     * root: a user-owned/writable session dir defeats the whole design. */
    if (enforce_owner_mode(fd, gid, 0750, "session dir") != 0) {
        close(fd);
        return -1;
    }
    return fd;
}

/* Build and write the metadata JSON for this session at dirfd/<name>.
 *
 * "exclusive" selects the two callers' very different needs (#198):
 *   - the INITIAL write creates the file and must never clobber an existing one:
 *     the name is <ts>_<session_id> and session_id is client-supplied, so a
 *     replayed session_id landing in the same second would otherwise truncate a
 *     live/finished session's metadata BEFORE the O_EXCL on the typescript gets
 *     the chance to reject the duplicate connection. Returns -2 on EEXIST so the
 *     caller can refuse the session exactly like a duplicate recording.
 *   - the FINAL write updates our own file in place (end time + status) and
 *     therefore truncates.
 * Returns 0 ok, -1 error, -2 already exists (exclusive only). */
static int write_metadata(int dirfd, const char *name, int exclusive,
                          const char *session_id,
                          const char *user, const char *client_ip, const char *tty,
                          const char *start, const char *end, const char *status,
                          const char *command, const char *format,
                          const char *recording_file, gid_t gid)
{
    struct json_object *o = json_object_new_object();
    json_object_object_add(o, "session_id", json_object_new_string(session_id));
    json_object_object_add(o, "user", json_object_new_string(user));
    json_object_object_add(o, "client_ip", json_object_new_string(client_ip ? client_ip : "unknown"));
    json_object_object_add(o, "tty", json_object_new_string(tty ? tty : "notty"));
    json_object_object_add(o, "start_time", json_object_new_string(start));
    json_object_object_add(o, "end_time", json_object_new_string(end ? end : ""));
    json_object_object_add(o, "status", json_object_new_string(status));
    json_object_object_add(o, "original_command", json_object_new_string(command ? command : ""));
    json_object_object_add(o, "format", json_object_new_string(format));
    json_object_object_add(o, "recording_file", json_object_new_string(recording_file));
    char host[256] = {0};
    if (gethostname(host, sizeof(host) - 1) != 0)
        snprintf(host, sizeof(host), "unknown");
    json_object_object_add(o, "hostname", json_object_new_string(host));
    json_object_object_add(o, "version", json_object_new_string(OB_RECORD_SINK_VERSION));

    const char *txt = json_object_to_json_string_ext(
        o, JSON_C_TO_STRING_PRETTY | JSON_C_TO_STRING_SPACED);
    size_t len = strlen(txt);

    int flags = O_WRONLY | O_CREAT | O_NOFOLLOW | (exclusive ? O_EXCL : O_TRUNC);
    int fd = openat(dirfd, name, flags, 0640);
    int ret = -1;
    if (fd < 0 && exclusive && errno == EEXIST) {
        json_object_put(o);
        return -2;
    }
    if (fd >= 0) {
        if (fchown(fd, 0, gid) != 0)
            fail("fchown(metadata) failed (continuing)");
        if (fchmod(fd, 0640) != 0)
            fail("fchmod(metadata) failed (continuing)");
        size_t off = 0;
        ret = 0;
        while (off < len) {
            ssize_t w = write(fd, txt + off, len - off);
            if (w < 0) {
                if (errno == EINTR)
                    continue;
                ret = -1;
                break;
            }
            off += (size_t)w;
        }
        if (write(fd, "\n", 1) < 0) {
            /* trailing newline is cosmetic; ignore failure */
        }
        close(fd);
    } else {
        fail("openat(metadata) failed");
    }
    json_object_put(o);
    return ret;
}

int main(void)
{
    /* Locate the connected socket (stdin if Accept=yes+StandardInput=socket,
     * else fd 3 under the sd_listen_fds protocol). Mirrors ob-cert-daemon. */
    int conn_fd = STDIN_FILENO;
    struct stat fdst;
    if (!(fstat(conn_fd, &fdst) == 0 && S_ISSOCK(fdst.st_mode))) {
        const char *lf = getenv("LISTEN_FDS");
        const char *lp = getenv("LISTEN_PID");
        if (lf && atoi(lf) >= 1 && lp && atoi(lp) == (int)getpid())
            conn_fd = 3;
    }

    struct timeval tv = {.tv_sec = HEADER_TIMEOUT_SEC, .tv_usec = 0};
    setsockopt(conn_fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    /* 1. Recorded user from the connection, kernel-verified. */
    struct ucred cred;
    socklen_t clen = sizeof(cred);
    if (getsockopt(conn_fd, SOL_SOCKET, SO_PEERCRED, &cred, &clen) != 0) {
        fail("SO_PEERCRED failed (not a socket?)");
        return 1;
    }
    char pwbuf[4096];
    struct passwd pw, *pwp = NULL;
    if (getpwuid_r(cred.uid, &pw, pwbuf, sizeof(pwbuf), &pwp) != 0 || !pwp) {
        fail("cannot resolve calling uid to a user");
        return 1;
    }
    char user[64];
    snprintf(user, sizeof(user), "%s", pw.pw_name);
    if (!ob_valid_username(user)) {
        fail("calling user name rejected by policy");
        return 1;
    }

    /* 2. Header line (one JSON object). */
    char hdrline[MAX_HEADER];
    ssize_t hn = ob_read_line(conn_fd, hdrline, sizeof(hdrline));
    if (hn <= 0) {
        fail("missing or oversized metadata header");
        return 1;
    }
    struct json_object *hdr = json_tokener_parse(hdrline);
    if (!hdr || !json_object_is_type(hdr, json_type_object)) {
        if (hdr)
            json_object_put(hdr);
        fail("malformed metadata header (not a JSON object)");
        return 1;
    }
    /* The header timeout ends here. The stream has no idle timeout at all: it
     * is read through poll(), which watches the peer as well as the socket. */
    tv.tv_sec = 0;
    setsockopt(conn_fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    char *session_id = hdr_str(hdr, "session_id", 64);
    char *format = hdr_str(hdr, "format", 32);
    char *client_ip = hdr_str(hdr, "client_ip", MAX_SHORT);
    char *tty = hdr_str(hdr, "ssh_tty", MAX_SHORT);
    char *command = hdr_str(hdr, "original_command", MAX_CMD);

    if (!session_id || !valid_session_id(session_id)) {
        fail("missing/invalid session_id in header");
        goto reject;
    }
    if (!format)
        format = strdup("script");
    /* Allowlist of recording formats understood by v1. */
    int is_transfer = strcmp(format, "transfer") == 0;
    if (strcmp(format, "script") != 0 && !is_transfer) {
        fail("unsupported recording format");
        goto reject;
    }

    gid_t gid = sessions_gid();
    int dirfd = ensure_user_dir(user, gid);
    if (dirfd < 0)
        goto reject;

    /* 3. Build file names: <ts>_<session_id>.{typescript,json} */
    char ts[32];
    {
        time_t t = time(NULL);
        struct tm tm;
        localtime_r(&t, &tm);
        strftime(ts, sizeof(ts), "%Y%m%d-%H%M%S", &tm);
    }
    char rec_name[160], meta_name[160];
    snprintf(rec_name, sizeof(rec_name), "%s_%s.typescript", ts, session_id);
    snprintf(meta_name, sizeof(meta_name), "%s_%s.json", ts, session_id);

    char start_time[32], end_time[32];
    iso_utc(start_time, sizeof(start_time));

    /* Write the initial metadata (status "active") so a killed sink still leaves
     * a record of the session having started. The lifecycle status is always
     * active → completed/truncated/aborted; the transfer vs script distinction
     * is carried by the "format" field, not the status.
     *
     * Created with O_EXCL: a duplicate <ts>_<session_id> must be refused here
     * rather than truncate an existing session's metadata (#198). Other write
     * failures are non-fatal, as before — the recording itself still matters. */
    if (write_metadata(dirfd, meta_name, 1, session_id, user, client_ip, tty,
                       start_time, NULL, "active",
                       command, format, rec_name, gid) == -2) {
        fail("metadata for this session id/timestamp already exists; refusing");
        goto reject_dir;
    }

    /* Create the recording file root-owned (root:ob-sessions 0640), no symlink,
     * no clobber. For a transfer session it stays an empty placeholder. */
    int recfd = openat(dirfd, rec_name, O_WRONLY | O_CREAT | O_EXCL | O_NOFOLLOW, 0640);
    if (recfd < 0) {
        fail("openat(recording) failed");
        goto reject_dir;
    }
    /* Fail closed as root if we cannot make the file root-owned: otherwise the
     * recorded user could later alter/delete it. */
    if (enforce_owner_mode(recfd, gid, 0640, "recording file") != 0) {
        close(recfd);
        goto reject_dir;
    }

    const char *status = "completed";
    if (!is_transfer) {
        /* 4. Stream copy, bounded by the peer's life, a total duration and a
         * byte cap -- never by silence. An interactive session that prints
         * nothing for a while is a live session: the idle timeout this
         * replaces (30 s, until #287) finalized such a recording as
         * "aborted", and the recorder then died of SIGPIPE at the user's
         * next keystroke. */
        long poll_sec = env_seconds("OB_RECORD_POLL_SEC", DEFAULT_POLL_SEC, 3600);
        long max_sec = env_seconds("OB_RECORD_MAX_SEC", DEFAULT_MAX_SESSION_SEC,
                                   LONG_MAX / 2);
        long deadline = mono_now() + max_sec;
        int pidfd = peer_pidfd(conn_fd, cred.pid);
        int peer_gone = 0;
        char buf[COPY_BUF];
        long total = 0;
        for (;;) {
            long left = deadline - mono_now();
            if (left <= 0) {
                status = "truncated";
                fail("recording hit the duration cap; finalizing as truncated");
                break;
            }
            long wait_sec = left < poll_sec ? left : poll_sec;
            struct pollfd pfds[2] = {
                {.fd = conn_fd, .events = POLLIN, .revents = 0},
                {.fd = pidfd, .events = POLLIN, .revents = 0},
            };
            nfds_t nfds = (pidfd >= 0 && !peer_gone) ? 2 : 1;
            int pr = poll(pfds, nfds, (int)(wait_sec * 1000));
            if (pr < 0) {
                if (errno == EINTR)
                    continue;
                status = "aborted";
                break;
            }
            if (pr == 0) {
                /* Idle. Only a dead peer ends the recording here: the
                 * connection outlived the process that opened it, so it is
                 * held by something else and nothing will ever close it. */
                if (peer_gone) {
                    fail("peer exited but its connection is still open; finalizing as aborted");
                    status = "aborted";
                    break;
                }
                if (pidfd < 0 && !pid_alive(cred.pid))
                    peer_gone = 1; /* one more interval to drain, then abort */
                continue;
            }
            /* The peer exiting is ordinary at the end of a session: keep
             * draining what the socket still holds. Its EOF, or the next idle
             * wake-up, decides. */
            if (nfds == 2 && pfds[1].revents)
                peer_gone = 1;
            if (!(pfds[0].revents & (POLLIN | POLLHUP | POLLERR)))
                continue;
            ssize_t r = read(conn_fd, buf, sizeof(buf));
            if (r < 0) {
                if (errno == EINTR || errno == EAGAIN)
                    continue;
                status = "aborted"; /* hard error -> abnormal end */
                break;
            }
            if (r == 0) {
                status = "completed"; /* clean EOF */
                break;
            }
            if (total + r > MAX_RECORDING) {
                /* Write what fits, then stop. */
                long room = MAX_RECORDING - total;
                if (room > 0) {
                    ssize_t off = 0;
                    while (off < room) {
                        ssize_t w = write(recfd, buf + off, (size_t)(room - off));
                        if (w < 0) {
                            if (errno == EINTR)
                                continue;
                            break;
                        }
                        off += w;
                    }
                }
                status = "truncated";
                fail("recording hit the size cap; finalizing as truncated");
                break;
            }
            ssize_t off = 0;
            while (off < r) {
                ssize_t w = write(recfd, buf + off, (size_t)(r - off));
                if (w < 0) {
                    if (errno == EINTR)
                        continue;
                    fail("write(recording) failed");
                    status = "aborted";
                    goto stream_done;
                }
                off += w;
            }
            total += r;
        }
    stream_done:
        if (pidfd >= 0)
            close(pidfd);
    } else {
        status = "completed"; /* transfer: metadata only, no stream */
    }
    close(recfd);

    /* 5. Final metadata with end time + observed status. */
    iso_utc(end_time, sizeof(end_time));
    write_metadata(dirfd, meta_name, 0, session_id, user, client_ip, tty,
                   start_time, end_time, status, command, format, rec_name, gid);

    close(dirfd);
    free(session_id);
    free(format);
    free(client_ip);
    free(tty);
    free(command);
    json_object_put(hdr);
    return 0;

reject_dir:
    close(dirfd);
reject:
    free(session_id);
    free(format);
    free(client_ip);
    free(tty);
    free(command);
    json_object_put(hdr);
    return 1;
}
