/*
 * ob-record-sink - privileged session-recording sink
 *
 * Socket-activated (systemd, Accept=yes): one short-lived instance per
 * connection. Implements the tamper-evident recording design
 * (doc/design/tamper-evident-session-recording.md, #151).
 *
 * The unprivileged ob-session-recorder (running as the logged-in user) connects
 * via ob-record-connect and sends:
 *   - line 1: a one-line JSON metadata HEADER, then
 *   - the opaque recording STREAM (typescript bytes) until EOF.
 *
 * This sink:
 *   1. derives the recorded user from the connection's SO_PEERCRED. This is the
 *      ONLY source of identity — kernel-verified, never from the header — so a
 *      caller can only ever write under its own name (no cross-user forgery,
 *      no path traversal: the <user> path component is not client-controlled).
 *   2. creates /var/lib/open-bastion/sessions/<user>/ (root:ob-sessions 0750)
 *      and writes the recording + metadata there, root-owned (files 0640). The
 *      recorded user is NOT in ob-sessions and the tree is o-rwx, so the user
 *      cannot list, read, unlink or truncate its own recording — which is the
 *      whole point (#151).
 *   3. records ONLY what it observes: status active -> completed (clean EOF) /
 *      truncated (size cap or timeout) / aborted (abnormal drop). The child
 *      command's exit code is deliberately not recorded (it would be entirely
 *      client-reported; see the design §5).
 *
 * Threat model: root is trusted; we defend only against the unprivileged user.
 *
 * Copyright (C) 2026 Linagora
 * License: AGPL-3.0
 */

#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <grp.h>
#include <pwd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>

#include <json-c/json.h>

#include "ob_cert_proto.h" /* ob_read_line, ob_valid_username */

#define OB_RECORD_SINK_VERSION "0.1.0"

#define SESSIONS_DIR "/var/lib/open-bastion/sessions"
#define SESSIONS_GROUP "ob-sessions"

/* Header line cap (one JSON object). */
#define MAX_HEADER 8192
/* Per-session recording byte cap: bound a hostile/runaway stream. Generous for
 * legitimate long interactive sessions; exceeding it finalizes as "truncated". */
#define MAX_RECORDING (1024L * 1024L * 1024L) /* 1 GiB */
/* Field bounds for header metadata (informational, JSON-escaped on output). */
#define MAX_CMD 8192
#define MAX_SHORT 256
/* Drop a stalled peer instead of pinning a per-connection process. */
#define IO_TIMEOUT_SEC 30
#define COPY_BUF (64 * 1024)

static void fail(const char *msg)
{
    /* stderr -> journal (StandardError=journal). Never log recording content. */
    fprintf(stderr, "[ob-record-sink] %s\n", msg);
}

/* A session-id is generated by the recorder (a UUID). Accept a conservative
 * charset/length so it is safe as a path component. */
static int valid_session_id(const char *s)
{
    if (!s || !*s || strlen(s) > 64)
        return 0;
    for (const char *p = s; *p; p++)
        if (!(isalnum((unsigned char)*p) || *p == '-' || *p == '_'))
            return 0;
    return 1;
}

/* Read a string field from the parsed header, bounded by max. Returns a malloc'd
 * copy (caller frees) or NULL when absent/too long/contains control chars other
 * than what json already decoded; control chars are tolerated (json-c re-escapes
 * on output) but length is enforced. */
static char *hdr_str(struct json_object *h, const char *key, size_t max)
{
    struct json_object *v;
    if (!json_object_object_get_ex(h, key, &v))
        return NULL;
    if (!json_object_is_type(v, json_type_string))
        return NULL;
    const char *s = json_object_get_string(v);
    if (!s || strlen(s) > max)
        return NULL;
    return strdup(s);
}

/* ISO-8601 UTC timestamp into buf. */
static void iso_utc(char *buf, size_t n)
{
    time_t t = time(NULL);
    struct tm tm;
    gmtime_r(&t, &tm);
    strftime(buf, n, "%Y-%m-%dT%H:%M:%SZ", &tm);
}

/* Resolve the ob-sessions gid; fall back to 0 (root) with a warning if absent
 * (the setup scripts create the group; a missing group must not relax to a
 * user-accessible mode). */
static gid_t sessions_gid(void)
{
    char buf[4096];
    struct group gr, *grp = NULL;
    if (getgrnam_r(SESSIONS_GROUP, &gr, buf, sizeof(buf), &grp) == 0 && grp)
        return grp->gr_gid;
    fail("group " SESSIONS_GROUP " not found; falling back to root group");
    return 0;
}

/* Base sessions directory. Hard-coded by default; OB_SESSIONS_DIR overrides it
 * for tests. This reads the DAEMON's own environment, which is set by the systemd
 * unit (not by the connecting client), so it is not an attacker-controlled
 * input. */
static const char *sessions_base(void)
{
    const char *e = getenv("OB_SESSIONS_DIR");
    return (e && *e) ? e : SESSIONS_DIR;
}

/* Ensure <base>/<user> exists, root:gid 0750, no symlinks. Returns a dir
 * fd (O_DIRECTORY|O_NOFOLLOW) on success, -1 on error. */
static int ensure_user_dir(const char *user, gid_t gid)
{
    char path[512];
    int n = snprintf(path, sizeof(path), "%s/%s", sessions_base(), user);
    if (n < 0 || (size_t)n >= sizeof(path)) {
        fail("session dir path too long");
        return -1;
    }

    int fd = open(path, O_RDONLY | O_DIRECTORY | O_NOFOLLOW);
    if (fd < 0) {
        if (mkdir(path, 0750) != 0 && errno != EEXIST) {
            fail("mkdir(session dir) failed");
            return -1;
        }
        fd = open(path, O_RDONLY | O_DIRECTORY | O_NOFOLLOW);
        if (fd < 0) {
            fail("open(session dir) after mkdir failed");
            return -1;
        }
    }
    /* Enforce ownership/mode on the fd (no TOCTOU, no symlink). */
    if (fchown(fd, 0, gid) != 0)
        fail("fchown(session dir) failed (continuing)");
    if (fchmod(fd, 0750) != 0)
        fail("fchmod(session dir) failed (continuing)");
    return fd;
}

/* Build and write the metadata JSON for this session at dirfd/<name>.
 * Overwrites if it already exists (our own file). Returns 0/-1. */
static int write_metadata(int dirfd, const char *name, const char *session_id,
                          const char *user, const char *client_ip, const char *tty,
                          const char *start, const char *end, const char *status,
                          const char *command, const char *format,
                          const char *recording_file, gid_t gid)
{
    struct json_object *o = json_object_new_object();
    json_object_object_add(o, "session_id", json_object_new_string(session_id));
    json_object_object_add(o, "user", json_object_new_string(user));
    json_object_object_add(o, "client_ip", json_object_new_string(client_ip ? client_ip : "unknown"));
    json_object_object_add(o, "tty", json_object_new_string(tty ? tty : "notty"));
    json_object_object_add(o, "start_time", json_object_new_string(start));
    json_object_object_add(o, "end_time", json_object_new_string(end ? end : ""));
    json_object_object_add(o, "status", json_object_new_string(status));
    json_object_object_add(o, "original_command", json_object_new_string(command ? command : ""));
    json_object_object_add(o, "format", json_object_new_string(format));
    json_object_object_add(o, "recording_file", json_object_new_string(recording_file));
    char host[256] = {0};
    if (gethostname(host, sizeof(host) - 1) != 0)
        snprintf(host, sizeof(host), "unknown");
    json_object_object_add(o, "hostname", json_object_new_string(host));
    json_object_object_add(o, "version", json_object_new_string(OB_RECORD_SINK_VERSION));

    const char *txt = json_object_to_json_string_ext(
        o, JSON_C_TO_STRING_PRETTY | JSON_C_TO_STRING_SPACED);
    size_t len = strlen(txt);

    int fd = openat(dirfd, name, O_WRONLY | O_CREAT | O_TRUNC | O_NOFOLLOW, 0640);
    int ret = -1;
    if (fd >= 0) {
        if (fchown(fd, 0, gid) != 0)
            fail("fchown(metadata) failed (continuing)");
        if (fchmod(fd, 0640) != 0)
            fail("fchmod(metadata) failed (continuing)");
        size_t off = 0;
        ret = 0;
        while (off < len) {
            ssize_t w = write(fd, txt + off, len - off);
            if (w < 0) {
                if (errno == EINTR)
                    continue;
                ret = -1;
                break;
            }
            off += (size_t)w;
        }
        if (write(fd, "\n", 1) < 0) {
            /* trailing newline is cosmetic; ignore failure */
        }
        close(fd);
    } else {
        fail("openat(metadata) failed");
    }
    json_object_put(o);
    return ret;
}

int main(void)
{
    /* Locate the connected socket (stdin if Accept=yes+StandardInput=socket,
     * else fd 3 under the sd_listen_fds protocol). Mirrors ob-cert-daemon. */
    int conn_fd = STDIN_FILENO;
    struct stat fdst;
    if (!(fstat(conn_fd, &fdst) == 0 && S_ISSOCK(fdst.st_mode))) {
        const char *lf = getenv("LISTEN_FDS");
        const char *lp = getenv("LISTEN_PID");
        if (lf && atoi(lf) >= 1 && lp && atoi(lp) == (int)getpid())
            conn_fd = 3;
    }

    struct timeval tv = {.tv_sec = IO_TIMEOUT_SEC, .tv_usec = 0};
    setsockopt(conn_fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));

    /* 1. Recorded user from the connection, kernel-verified. */
    struct ucred cred;
    socklen_t clen = sizeof(cred);
    if (getsockopt(conn_fd, SOL_SOCKET, SO_PEERCRED, &cred, &clen) != 0) {
        fail("SO_PEERCRED failed (not a socket?)");
        return 1;
    }
    char pwbuf[4096];
    struct passwd pw, *pwp = NULL;
    if (getpwuid_r(cred.uid, &pw, pwbuf, sizeof(pwbuf), &pwp) != 0 || !pwp) {
        fail("cannot resolve calling uid to a user");
        return 1;
    }
    char user[64];
    snprintf(user, sizeof(user), "%s", pw.pw_name);
    if (!ob_valid_username(user)) {
        fail("calling user name rejected by policy");
        return 1;
    }

    /* 2. Header line (one JSON object). */
    char hdrline[MAX_HEADER];
    ssize_t hn = ob_read_line(conn_fd, hdrline, sizeof(hdrline));
    if (hn <= 0) {
        fail("missing or oversized metadata header");
        return 1;
    }
    struct json_object *hdr = json_tokener_parse(hdrline);
    if (!hdr || !json_object_is_type(hdr, json_type_object)) {
        if (hdr)
            json_object_put(hdr);
        fail("malformed metadata header (not a JSON object)");
        return 1;
    }

    char *session_id = hdr_str(hdr, "session_id", 64);
    char *format = hdr_str(hdr, "format", 32);
    char *client_ip = hdr_str(hdr, "client_ip", MAX_SHORT);
    char *tty = hdr_str(hdr, "ssh_tty", MAX_SHORT);
    char *command = hdr_str(hdr, "original_command", MAX_CMD);

    if (!session_id || !valid_session_id(session_id)) {
        fail("missing/invalid session_id in header");
        goto reject;
    }
    if (!format)
        format = strdup("script");
    /* Allowlist of recording formats understood by v1. */
    int is_transfer = strcmp(format, "transfer") == 0;
    if (strcmp(format, "script") != 0 && !is_transfer) {
        fail("unsupported recording format");
        goto reject;
    }

    gid_t gid = sessions_gid();
    int dirfd = ensure_user_dir(user, gid);
    if (dirfd < 0)
        goto reject;

    /* 3. Build file names: <ts>_<session_id>.{typescript,json} */
    char ts[32];
    {
        time_t t = time(NULL);
        struct tm tm;
        localtime_r(&t, &tm);
        strftime(ts, sizeof(ts), "%Y%m%d-%H%M%S", &tm);
    }
    char rec_name[160], meta_name[160];
    snprintf(rec_name, sizeof(rec_name), "%s_%s.typescript", ts, session_id);
    snprintf(meta_name, sizeof(meta_name), "%s_%s.json", ts, session_id);

    char start_time[32], end_time[32];
    iso_utc(start_time, sizeof(start_time));

    /* Write the initial metadata (status active) so a killed sink still leaves a
     * record of the session having started. */
    write_metadata(dirfd, meta_name, session_id, user, client_ip, tty,
                   start_time, NULL, is_transfer ? "transfer" : "active",
                   command, format, rec_name, gid);

    /* Create the recording file root-owned (root:ob-sessions 0640), no symlink,
     * no clobber. For a transfer session it stays an empty placeholder. */
    int recfd = openat(dirfd, rec_name, O_WRONLY | O_CREAT | O_EXCL | O_NOFOLLOW, 0640);
    if (recfd < 0) {
        fail("openat(recording) failed");
        goto reject_dir;
    }
    if (fchown(recfd, 0, gid) != 0)
        fail("fchown(recording) failed (continuing)");
    if (fchmod(recfd, 0640) != 0)
        fail("fchmod(recording) failed (continuing)");

    const char *status = "completed";
    if (!is_transfer) {
        /* 4. Stream copy with a byte cap and the recv timeout set above. */
        char buf[COPY_BUF];
        long total = 0;
        for (;;) {
            ssize_t r = read(conn_fd, buf, sizeof(buf));
            if (r < 0) {
                if (errno == EINTR)
                    continue;
                /* timeout (EAGAIN/EWOULDBLOCK) or hard error -> abnormal end */
                status = "aborted";
                break;
            }
            if (r == 0) {
                status = "completed"; /* clean EOF */
                break;
            }
            if (total + r > MAX_RECORDING) {
                /* Write what fits, then stop. */
                long room = MAX_RECORDING - total;
                if (room > 0) {
                    ssize_t off = 0;
                    while (off < room) {
                        ssize_t w = write(recfd, buf + off, (size_t)(room - off));
                        if (w < 0) {
                            if (errno == EINTR)
                                continue;
                            break;
                        }
                        off += w;
                    }
                }
                status = "truncated";
                fail("recording hit the size cap; finalizing as truncated");
                break;
            }
            ssize_t off = 0;
            while (off < r) {
                ssize_t w = write(recfd, buf + off, (size_t)(r - off));
                if (w < 0) {
                    if (errno == EINTR)
                        continue;
                    fail("write(recording) failed");
                    status = "aborted";
                    goto stream_done;
                }
                off += w;
            }
            total += r;
        }
    stream_done:;
    } else {
        status = "completed"; /* transfer: metadata only, no stream */
    }
    close(recfd);

    /* 5. Final metadata with end time + observed status. */
    iso_utc(end_time, sizeof(end_time));
    write_metadata(dirfd, meta_name, session_id, user, client_ip, tty,
                   start_time, end_time, status, command, format, rec_name, gid);

    close(dirfd);
    free(session_id);
    free(format);
    free(client_ip);
    free(tty);
    free(command);
    json_object_put(hdr);
    return 0;

reject_dir:
    close(dirfd);
reject:
    free(session_id);
    free(format);
    free(client_ip);
    free(tty);
    free(command);
    json_object_put(hdr);
    return 1;
}
